Add tests for relative paths in setup.py (#57)
* Update build tests to include `setup.py` calls from an absolute path

* Fix typo in repo checkout

* Update checkout to relative path in writable directory

* Troubleshoot passing tests

* Rename added job

* Add input to skip relative path tests

* Remove extra call in relative path build test

diff --git a/.github/workflows/python_build_tests.yml b/.github/workflows/python_build_tests.yml
--- a/.github/workflows/python_build_tests.yml
+++ b/.github/workflows/python_build_tests.yml
@@ -20,6 +20,9 @@ on:
       test_pipaudit:
         type: boolean
         default: false
+      test_relative_paths:
+        type: boolean
+        default: true
       pipaudit_ignored:
         type: string
         default: "GHSA-r9hx-vwmv-q579 PYSEC-2022-43012"
@@ -28,7 +31,8 @@ jobs:
     timeout-minutes: 15
     runs-on: ${{inputs.runner}}
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout Repository
+        uses: actions/checkout@v2
       - name: Set up python ${{ inputs.python_version }}
         uses: actions/setup-python@v2
         with:
@@ -49,3 +53,22 @@ jobs:
         uses: pypa/gh-action-pip-audit@v1.0.7
         with:
           ignore-vulns: ${{ inputs.pipaudit_ignored }}
+  relative_path_tests:
+    timeout-minutes: 15
+    runs-on: ${{inputs.runner}}
+    if: ${{ inputs.test_relative_paths }}
+    steps:
+      - name: Checkout Repository to build_test
+        uses: actions/checkout@v2
+        with:
+          path: build_test
+      - name: Set up python ${{ inputs.python_version }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ inputs.python_version }}
+      - name: Install Build Tools
+        run: |
+          python -m pip install build wheel
+      - name: Build Distribution Packages
+        run: |
+          python build_test/setup.py bdist_wheel sdist || echo "::error setup.py:: Are there relative paths in setup.py?"
